apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
- ../../base

patches:
- path: configmap.yaml

namePrefix: staging-

images:
- name: PROJECT/APP
  newName: ronaldidro/todo-app
  newTag: 95992e61836862ad0852fe3ccfb95abff90a634f
- name: PROJECT/BACKEND
  newName: ronaldidro/todo-backend
  newTag: 95992e61836862ad0852fe3ccfb95abff90a634f
- name: PROJECT/BACKUP
  newName: ronaldidro/todo-db-backup
- name: PROJECT/BROADCASTER
  newName: ronaldidro/todo-broadcaster
  newTag: 95992e61836862ad0852fe3ccfb95abff90a634f
- name: PROJECT/CRONJOB
  newName: ronaldidro/todo-generator
  newTag: 95992e61836862ad0852fe3ccfb95abff90a634f
- name: PROJECT/DB
  newName: postgres
  newTag: "14"
