apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
- ../../manifests

patches:
- path: configmap.yaml

namePrefix: staging-

images:
- name: PROJECT/APP
  newName: ronaldidro/todo-app
  newTag: 66734d4842064b4ad0fb6bb16ad21f59acee0e1c
- name: PROJECT/BACKEND
  newName: ronaldidro/todo-backend
  newTag: 66734d4842064b4ad0fb6bb16ad21f59acee0e1c
- name: PROJECT/BACKUP
  newName: ronaldidro/todo-db-backup
- name: PROJECT/BROADCASTER
  newName: ronaldidro/todo-broadcaster
  newTag: 66734d4842064b4ad0fb6bb16ad21f59acee0e1c
- name: PROJECT/CRONJOB
  newName: ronaldidro/todo-generator
  newTag: 66734d4842064b4ad0fb6bb16ad21f59acee0e1c
- name: PROJECT/DB
  newName: postgres
  newTag: "14"
