apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-prod
resources:
- ../../base
patches:
- path: configmap.yaml
namePrefix: prod-
images:
- name: PROJECT/APP
  newName: ronaldidro/todo-app
  newTag: "5.1"
- name: PROJECT/BACKEND
  newName: ronaldidro/todo-backend
  newTag: "5.1"
- name: PROJECT/BACKUP
  newName: ronaldidro/todo-db-backup
- name: PROJECT/BROADCASTER
  newName: ronaldidro/todo-broadcaster
  newTag: "5.1"
- name: PROJECT/CRONJOB
  newName: ronaldidro/todo-generator
  newTag: "5.1"
- name: PROJECT/DB
  newName: postgres
  newTag: "14"
