apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
data:
  APP_PORT: "3000"
  PICSUM_URL: "https://picsum.photos"
  BACKEND_PORT: "3001"
  BACKEND_SERVICE_URL: "http://todo-backend-svc:2560"
  PG_HOST: "postgres-stset-0.postgres-svc"
  PG_USER: "postgres"
  PG_PASSWORD: "postgres"
  NATS_URL: "nats://my-nats.default.svc.cluster.local:4222"
