apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - cronjob.yaml
  - ingress.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - todo-app/deployment.yaml
  - todo-app/service.yaml
  - todo-backend/deployment.yaml
  - todo-backend/service.yaml
  - todo-backend/statefulset.yaml
  - todo-broadcaster/deployment.yaml
